# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=50)),
                ('songname', models.CharField(max_length=50)),
                ('chords', models.CharField(max_length=15)),
                ('strummingpattern', models.CharField(max_length=50)),
            ],
        ),
    ]
