# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chords',
            field=models.FileField(max_length=255, upload_to='media/'),
        ),
    ]
