# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0002_auto_20161204_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='howmanychords',
            field=models.CharField(choices=[('one chord', '1'), ('two chord', '2'), ('three chord', '3'), ('four chord', '4'), ('five chord', '5'), ('six chord', '6')], default='', max_length=6),
        ),
    ]
