# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chords', '0003_song_howmanychords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='chords',
        ),
        migrations.AddField(
            model_name='song',
            name='songchord1',
            field=models.FileField(default='', max_length=255, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songchord2',
            field=models.FileField(default='', editable=False, max_length=255, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songchord3',
            field=models.FileField(default='', editable=False, max_length=255, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songchord4',
            field=models.FileField(default='', editable=False, max_length=255, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songchord5',
            field=models.FileField(default='', editable=False, max_length=255, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songchord6',
            field=models.FileField(default='', editable=False, max_length=255, upload_to='media/'),
        ),
    ]
